<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleblog"
 *
 * Auto generated by Extension Builder 2015-12-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple Blog Extension',
	'description' => 'This is the didactical example from the book \"Extbase & Fluid\" by Patrick Lobacher',
	'category' => 'plugin',
	'author' => 'Patrick Lobacher',
	'author_email' => 'patrick.lobacher@typovision.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);